### ISSUE TITLE
404 Error on page.

### ISSUE THREAD

**Issue by Norpordorp** [mariogamer2/rxtools-prebuilt#1]
So I followed the guide all the way through, and when I try to click any link it says 'Not Found. The requested URL /dukesrg.no-ip.org/ was not found on this server.' I have no idea what to do now. Help!

**Comment by mariogamer2** [comment]
In reality,the link can change like:

https://yourlocalhost/duke....

For the real sit of dukesrg,you can go:

http://dukesrg.github.io/?rxTools/sys/code.bin
http://dukesrg.github.io/?rxinstaller.bin
